export default [
  { tag: 'Whiskey', type: 'ingredient' },
  { tag: 'Gin', type: 'ingredient' },
  { tag: 'Rum', type: 'ingredient' },
  { tag: 'Vodka', type: 'ingredient' },
  { tag: 'Tequila', type: 'ingredient' },
  { tag: 'Effervescent', type: 'adjective' },
  { tag: 'Dry', type: 'adjective' },
  { tag: 'Frothy', type: 'adjective' },
  { tag: 'Smokey', type: 'adjective' },
  { tag: 'Spicy', type: 'adjective' },
  { tag: 'Sour', type: 'adjective' },
  { tag: 'Sweet', type: 'adjective' },
  { tag: 'Spirit Forward', type: 'adjective' },
  { tag: 'Classic', type: 'adjective' },
  { tag: 'Exotic', type: 'adjective' },
  { tag: 'Bitter', type: 'adjective' },
  { tag: 'Fruity', type: 'adjective' },
  { tag: 'Refreshing', type: 'adjective' },
  { tag: 'Floral', type: 'adjective' },
  { tag: 'Herbal', type: 'adjective' },
  { tag: 'Simple', type: 'adjective' },
  { tag: 'Complex', type: 'adjective' },
  { tag: 'Silky', type: 'adjective' },
  { tag: 'Rich', type: 'adjective' },
];

